#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: logdone
#+COLUMNS: %38ITEM(Details) %7TODO(To Do) %TAGS(Context) 
#+OPTIONS: tags:t timestamp:t todo:t TeX:t LaTeX:t          
#+OPTIONS: skip:t @:t ::t |:t ^:t f:t
* Package XLUniv

[[https://opensource.org/licenses/MIT][https://img.shields.io/badge/License-MIT-yellow.svg]]


  The XLUniv package provides a collection of excel workbooks for managing students in a French University (UNS).
  
  You must choose between installing the package from github or from source (for more advanced users).

* Prerequisites
  This project works on 32 bits and 64 bits environment. 
  This project requires:
  
  - [[http://cran.r-project.org/][R]] 3.2+
  - Downloaded and installed via the R function ~install.packages~.
    - [[https://cran.r-project.org/web/packages/devtools/index.html][devtools]]: Tools to Make Developing R Packages Easier (Build and Install only)

* Installing
** From Github

   Install directly from github without downloading a local copy the project.
   #+BEGIN_SRC R 
     install.packages("devtools") # if needed
     library(devtools)
     devtools::install_github("arnaud-m/XLUniv")
   #+END_SRC
  	
** From Source  
  
   Download a local copy of the project, open a R session in the project directory, and execute.
   #+BEGIN_SRC R 
     install.packages("devtools") # if needed
     library(devtools)
     devtools::install()
   #+END_SRC
   Check the [[https://www.rstudio.com/wp-content/uploads/2015/03/devtools-cheatsheet.pdf][devtools Cheat Sheet]]. 

* TODO Executing

 Once the project has been installed (see "Installing"), execute the example of 
#+BEGIN_SRC R
  library(XLUniv)
#+END_SRC

* Documentation
 
  Look for general information about the package in the R console.
   #+BEGIN_SRC R
     library(help=XLUniv)
   #+END_SRC

   Look for the package documentation in the R console.
   # #+BEGIN_SRC R
   #   library(XLUniv)
   # #+END_SRC
 
* License

  Copyright (c) 2018, Arnaud Malapert, Université Côte d'Azur, CNRS, I3S, France
  
  This software is distributed under a MIT License.    


  
